Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Models/Plugins/LicenseLabelModel.cs
using SmartStore.Licensing;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Admin.Models.Plugins
{
	public class LicenseLabelModel : ModelBase
	{
		public string LicenseUrl { get; set; }
		public bool IsLicensable { get; set; }
		public bool HideLabel { get; set; }
		public LicensingState LicenseState { get; set; }
		public string TruncatedLicenseKey { get; set; }
		public int? RemainingDemoUsageDays { get; set; }

		public string RemainingDemoUsageDaysLabel
		{
			get
			{
				if (RemainingDemoUsageDays.HasValue)
				{
					if (RemainingDemoUsageDays <= 3)
						return "badge-dark";

					if (RemainingDemoUsageDays <= 6)
						return "badge-warning";
				}
				return "badge-success";
			}
		}
	}
}

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Models/Plugins/LicensePluginModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Admin.Models.Plugins
{
	public class LicensePluginModel : ModelBase
	{
		public string SystemName { get; set; }
		public int InvalidDataStoreId { get; set; }

		public List<StoreLicenseModel> StoreLicenses { get; set; }

		public class StoreLicenseModel
		{
			public StoreLicenseModel()
			{
				LicenseLabel = new LicenseLabelModel();
			}

			[SmartResourceDisplayName("Admin.Configuration.Plugins.LicenseKey")]
			public string LicenseKey { get; set; }

			public LicenseLabelModel LicenseLabel { get; set; }

			public int StoreId { get; set; }
			public string StoreName { get; set; }
			public string StoreUrl { get; set; }
		}
	}
}

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Controllers/PluginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using SmartStore.Admin.Models.Plugins;
using SmartStore.Core.Domain.Cms;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Payments;
using SmartStore.Core.Domain.Security;
using SmartStore.Core.Domain.Shipping;
using SmartStore.Core.Domain.Tax;
using SmartStore.Core.Html;
using SmartStore.Core.Logging;
using SmartStore.Core.Plugins;
using SmartStore.Licensing;
using SmartStore.Services;
using SmartStore.Services.Authentication.External;
using SmartStore.Services.Cms;
using SmartStore.Services.Localization;
using SmartStore.Services.Payments;
using SmartStore.Services.Security;
using SmartStore.Services.Shipping;
using SmartStore.Services.Tax;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Plugins;
using SmartStore.Web.Framework.Security;

namespace SmartStore.Admin.Controllers
{
	[AdminAuthorize]
    public partial class PluginController : AdminControllerBase
	{
		#region Fields

        private readonly IPluginFinder _pluginFinder;
        private readonly IPermissionService _permissionService;
        private readonly ILanguageService _languageService;
        private readonly PaymentSettings _paymentSettings;
        private readonly ShippingSettings _shippingSettings;
        private readonly TaxSettings _taxSettings;
        private readonly ExternalAuthenticationSettings _externalAuthenticationSettings;
        private readonly WidgetSettings _widgetSettings;
		private readonly IProviderManager _providerManager;
		private readonly PluginMediator _pluginMediator;
		private readonly ICommonServices _services;

	    #endregion

		#region Constructors

        public PluginController(IPluginFinder pluginFinder,
            IPermissionService permissionService,
			ILanguageService languageService,
            PaymentSettings paymentSettings,
			ShippingSettings shippingSettings,
            TaxSettings taxSettings, 
			ExternalAuthenticationSettings externalAuthenticationSettings, 
            WidgetSettings widgetSettings,
			IProviderManager providerManager,
			PluginMediator pluginMediator,
			ICommonServices services)
		{
            this._pluginFinder = pluginFinder;
            this._permissionService = permissionService;
            this._languageService = languageService;
            this._paymentSettings = paymentSettings;
            this._shippingSettings = shippingSettings;
            this._taxSettings = taxSettings;
            this._externalAuthenticationSettings = externalAuthenticationSettings;
            this._widgetSettings = widgetSettings;
			this._providerManager = providerManager;
			this._pluginMediator = pluginMediator;
			this._services = services;
		}

        #endregion

        #region Utilities

        private bool IsLicensable(PluginDescriptor pluginDescriptor)
        {
            var result = false;

            try
            {
                result = LicenseChecker.IsLicensablePlugin(pluginDescriptor);
            }
            catch (Exception ex)
            {
                Logger.Error(ex);
            }

            return result;
        }

        private LicensingData PrepareLicenseLabelModel(LicenseLabelModel model, PluginDescriptor pluginDescriptor, string url = null)
		{
            if (IsLicensable(pluginDescriptor))
			{
				// We always show license button to serve ability to delete a key.
				model.IsLicensable = true;
				model.LicenseUrl = Url.Action("LicensePlugin", new { systemName = pluginDescriptor.SystemName });

				var license = LicenseChecker.GetLicense(pluginDescriptor.SystemName, url);
				if (license == null)
				{
					// Licensed plugin has not been used yet -> Check state.
					var unused = LicenseChecker.CheckState(pluginDescriptor.SystemName, url);

					// And try to get license data again.
					license = LicenseChecker.GetLicense(pluginDescriptor.SystemName, url);
				}

				if (license != null)
				{
					// Licensed plugin has been used.
					model.LicenseState = license.State;
					model.TruncatedLicenseKey = license.TruncatedLicenseKey;
					model.RemainingDemoUsageDays = license.RemainingDemoDays;
				}
				else
				{
					// It's confusing to display a license state when there is no license data yet.
					model.HideLabel = true;
				}

				return license;
			}

			return null;
		}

		[NonAction]
        protected PluginModel PreparePluginModel(PluginDescriptor pluginDescriptor, bool forList = true)
        {
            var model = pluginDescriptor.ToModel();

			// Using GetResource because T could fallback to NullLocalizer here.
			model.Group = _services.Localization.GetResource("Admin.Plugins.KnownGroup." + pluginDescriptor.Group);

			if (forList)
			{
				model.FriendlyName = pluginDescriptor.GetLocalizedValue(_services.Localization, "FriendlyName");
				model.Description = pluginDescriptor.GetLocalizedValue(_services.Localization, "Description");
			}

            // Locales
            AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
				locale.FriendlyName = pluginDescriptor.GetLocalizedValue(_services.Localization, "FriendlyName", languageId, false);
				locale.Description = pluginDescriptor.GetLocalizedValue(_services.Localization, "Description", languageId, false);
            });

			// Stores
			model.SelectedStoreIds = _services.Settings.GetSettingByKey<string>(pluginDescriptor.GetSettingKey("LimitedToStores")).ToIntArray();

			// Icon
			model.IconUrl = _pluginMediator.GetIconUrl(pluginDescriptor);
            
            if (pluginDescriptor.Installed)
            {
                // specify configuration URL only when a plugin is already installed
				if (pluginDescriptor.IsConfigurable)
				{
					model.ConfigurationUrl = Url.Action("ConfigurePlugin", new { systemName = pluginDescriptor.SystemName });

					if (!forList)
					{
						var configurable = pluginDescriptor.Instance() as IConfigurable;

						string actionName;
						string controllerName;
						RouteValueDictionary routeValues;
						configurable.GetConfigurationRoute(out actionName, out controllerName, out routeValues);

						if (actionName.HasValue() && controllerName.HasValue())
						{
							model.ConfigurationRoute = new RouteInfo(actionName, controllerName, routeValues);
						}
					}
				}

				// License label
				PrepareLicenseLabelModel(model.LicenseLabel, pluginDescriptor);
            }

            return model;
        }

        [NonAction]
        protected LocalPluginsModel PrepareLocalPluginsModel()
        {
            var plugins = _pluginFinder.GetPluginDescriptors(false)
                .OrderBy(p => p.Group, PluginFileParser.KnownGroupComparer)
                .ThenBy(p => p.DisplayOrder)
                .Select(x => PreparePluginModel(x));

			var model = new LocalPluginsModel();

			model.AvailableStores = _services.StoreService
				.GetAllStores()
				.Select(s => s.ToModel())
				.ToList();

            var groupedPlugins = from p in plugins
                                 group p by p.Group into g
                                 select g;

            foreach (var group in groupedPlugins)
            {
                foreach (var plugin in group)
                {
                    model.Groups.Add(group.Key, plugin);
                }
            }

            return model;
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePlugins))
                return AccessDeniedView();

            var model = PrepareLocalPluginsModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult ExecuteTasks(IEnumerable<string> pluginsToInstall, IEnumerable<string> pluginsToUninstall)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePlugins))
                return AccessDeniedView();

            try
            {
                int tasksCount = 0;
                IEnumerable<PluginDescriptor> descriptors = null;

                // Uninstall first
                if (pluginsToUninstall != null && pluginsToUninstall.Any())
                {
                    descriptors = _pluginFinder.GetPluginDescriptors(false).Where(x => pluginsToUninstall.Contains(x.SystemName));
                    foreach (var d in descriptors)
                    {
                        if (d.Installed)
                        {
                            d.Instance().Uninstall();
                            tasksCount++;
                        }
                    }
                }

                // now execute installations
                if (pluginsToInstall != null && pluginsToInstall.Any())
                {
                    descriptors = _pluginFinder.GetPluginDescriptors(false).Where(x => pluginsToInstall.Contains(x.SystemName));
                    foreach (var d in descriptors)
                    {
                        if (!d.Installed)
                        {
                            d.Instance().Install();
                            tasksCount++;
                        }
                    }
                }

                // restart application
                if (tasksCount > 0)
                {
					_services.WebHelper.RestartAppDomain(aggressive: true);
                }
            }
            catch (Exception exc)
            {
                NotifyError(exc);
            }

            return RedirectToAction("List");
        }

        public ActionResult ReloadList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePlugins))
                return AccessDeniedView();

            // restart application

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Controllers/StoreController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Admin.Models.Stores;
using SmartStore.Core.Domain.Stores;
using SmartStore.Services.Directory;
using SmartStore.Services.Media;
using SmartStore.Services.Security;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Security;
using Telerik.Web.Mvc;

namespace SmartStore.Admin.Controllers
{
	[AdminAuthorize]
	public partial class StoreController : AdminControllerBase
	{
		private readonly ICurrencyService _currencyService;

		public StoreController(ICurrencyService currencyService)
		{
			_currencyService = currencyService;
		}

		private void PrepareStoreModel(StoreModel model, Store store)
		{
			model.AvailableCurrencies = _currencyService.GetAllCurrencies(false, store == null ? 0 : store.Id)
				.Select(x => new SelectListItem
				{
					Text = x.Name,
					Value = x.Id.ToString()
				})
				.ToList();
		}

		public ActionResult List()
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			return View();
		}

		public ActionResult AllStores(string label, int selectedId = 0)
		{
			var stores = Services.StoreService.GetAllStores();

			if (label.HasValue())
			{
				stores.Insert(0, new Store { Name = label, Id = 0 });
			}

			var list = 
				from m in stores
				select new
				{
					id = m.Id.ToString(),
					text = m.Name,
					selected = m.Id == selectedId
				};

			return new JsonResult { Data = list.ToList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
		}

		[HttpPost, GridAction(EnableCustomBinding = true)]
		public ActionResult List(GridCommand command)
		{
			var gridModel = new GridModel<StoreModel>();

			if (Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
			{
				var storeModels = Services.StoreService.GetAllStores()
					.Select(x =>
					{
						var model = x.ToModel();

						PrepareStoreModel(model, x);

						model.Hosts = model.Hosts.EmptyNull().Replace(",", "<br />");

						return model;
					})
					.ToList();

				gridModel.Data = storeModels;
				gridModel.Total = storeModels.Count();
			}
			else
			{
				gridModel.Data = Enumerable.Empty<StoreModel>();

				NotifyAccessDenied();
			}

			return new JsonResult
			{
				Data = gridModel
			};
		}

		public ActionResult Create()
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			var model = new StoreModel();
			PrepareStoreModel(model, null);

			return View(model);
		}

		[HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
		public ActionResult Create(StoreModel model, bool continueEditing)
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			if (ModelState.IsValid)
			{
				var store = model.ToEntity();
				MediaHelper.UpdatePictureTransientStateFor(store, s => s.LogoPictureId);
				//ensure we have "/" at the end
				store.Url = store.Url.EnsureEndsWith("/");
				Services.StoreService.InsertStore(store);

				NotifySuccess(T("Admin.Configuration.Stores.Added"));
				return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
			}

			//If we got this far, something failed, redisplay form
			PrepareStoreModel(model, null);
			return View(model);
		}

		public ActionResult Edit(int id)
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			var store = Services.StoreService.GetStoreById(id);
			if (store == null)
				return RedirectToAction("List");

			var model = store.ToModel();
			PrepareStoreModel(model, store);

			return View(model);
		}

		[HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
		[FormValueRequired("save", "save-continue")]
		public ActionResult Edit(StoreModel model, bool continueEditing)
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			var store = Services.StoreService.GetStoreById(model.Id);
			if (store == null)
				return RedirectToAction("List");

			if (ModelState.IsValid)
			{
				store = model.ToEntity(store);

				MediaHelper.UpdatePictureTransientStateFor(store, s => s.LogoPictureId);

				//ensure we have "/" at the end
				store.Url = store.Url.EnsureEndsWith("/");
				Services.StoreService.UpdateStore(store);

				NotifySuccess(T("Admin.Configuration.Stores.Updated"));
				return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
			}

			//If we got this far, something failed, redisplay form
			PrepareStoreModel(model, store);
			return View(model);
		}

		[HttpPost]
		public ActionResult Delete(int id)
		{
			if (!Services.Permissions.Authorize(StandardPermissionProvider.ManageStores))
				return AccessDeniedView();

			var store = Services.StoreService.GetStoreById(id);
			if (store == null)
				return RedirectToAction("List");

			try
			{
				Services.StoreService.DeleteStore(store);

				//when we delete a store we should also ensure that all "per store" settings will also be deleted
				var settingsToDelete = Services.Settings
					.GetAllSettings()
					.Where(s => s.StoreId == id)
					.ToList();

				settingsToDelete.ForEach(x => Services.Settings.DeleteSetting(x));

				//when we had two stores and now have only one store, we also should delete all "per store" settings
				var allStores = Services.StoreService.GetAllStores();

				if (allStores.Count == 1)
				{
					settingsToDelete = Services.Settings
						.GetAllSettings()
						.Where(s => s.StoreId == allStores[0].Id)
						.ToList();

					settingsToDelete.ForEach(x => Services.Settings.DeleteSetting(x));
				}

				NotifySuccess(T("Admin.Configuration.Stores.Deleted"));
				return RedirectToAction("List");
			}
			catch (Exception exc)
			{
				NotifyError(exc);
			}
			return RedirectToAction("Edit", new { id = store.Id });
		}
	}
}

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Views/Plugin/ConfigurePlugin.cshtml
@model PluginModel

@{
	ViewBag.Title = T("Admin.Common.Configure").Text + " - " + Model.FriendlyName;
}

<script>
	$(function () {
		SmartStore.Admin.movePluginActionButtons();
	});
</script>

<div class="section-header">
	<div class="title" title="@ViewBag.Title (@Model.SystemName)">
		<img src="@Url.Content(Model.IconUrl)" alt="@Model.FriendlyName" />
		@ViewBag.Title
		<a href='@Url.Action("List")'>(@T("Admin.Common.BackToList"))</a>
	</div>
	<div class="options">	
		<a class="btn btn-secondary" href='@Url.Action("UpdateStringResources", new { systemName = Model.SystemName, returnUrl = Request.RawUrl })'>
			<i class="fa fa-sync"></i>
			<span>@T("Admin.Configuration.Plugins.Resources.Update")</span>
		</a>
	</div>
</div>

<div class="plugin-config-container">
	@if (Model.ConfigurationRoute != null && Model.ConfigurationRoute.Action.HasValue())
	{
		try
		{
			Html.RenderAction(Model.ConfigurationRoute.Action, Model.ConfigurationRoute.Controller, Model.ConfigurationRoute.RouteValues);
		}
		catch (Exception exception)
		{
			<div class="alert alert-danger">
				@T("Admin.Configuration.Plugins.UnknownError")
			</div>

			<pre>@exception.ToString()</pre>
		}
	}
	else
	{
		@T("Admin.Common.ConfigurationNotRequired")
	}
</div>

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Views/Plugin/ConfigureProvider.cshtml
@model SmartStore.Web.Framework.Plugins.ProviderModel

@{    
    ViewBag.Title = T("Admin.Common.Configure").Text + " - " + Model.FriendlyName;
}

<script>
	$(function () {
		SmartStore.Admin.movePluginActionButtons();
	});
</script>

<div class="section-header">
    <div class="title" title="@ViewBag.Title (@Model.SystemName)">
		<img src="@Url.Content(Model.IconUrl)" alt="@Model.FriendlyName" />
        @ViewBag.Title
		<a href="@ViewBag.ListUrl">(@T("Admin.Common.BackToList"))</a>
    </div>
	@if (Model.PluginDescriptor != null)
	{
		<div class="options">
			<a class="btn btn-secondary" href='@Url.Action("UpdateStringResources", "Plugin", new { systemName = Model.PluginDescriptor.SystemName, returnUrl = Request.RawUrl })'>
				<i class="fa fa-sync"></i>
				<span>@T("Admin.Configuration.Plugins.Resources.Update")</span>
			</a>
		</div>		
	}
</div>

<div class="plugin-config-container">
	@if (Model.ConfigurationRoute != null && Model.ConfigurationRoute.Action.HasValue())
	{
		try
		{
			Html.RenderAction(Model.ConfigurationRoute.Action, Model.ConfigurationRoute.Controller, Model.ConfigurationRoute.RouteValues);
		}
		catch (Exception exception)
		{
			<div class="alert alert-danger">
				@T("Admin.Configuration.Plugins.UnknownError")
			</div>

			<pre>@exception.ToString()</pre>
		}
	}
	else
	{
		@T("Admin.Common.ConfigurationNotRequired")
	}
</div>

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Views/Plugin/EditProviderPopup.cshtml
@using SmartStore.Web.Framework.Plugins
@model SmartStore.Web.Framework.Plugins.ProviderModel

@{
	Layout = "_AdminPopupLayout";
	ViewBag.Title = string.Concat(T("Common.Edit"), " - ", ((ViewBag.Title as string) ?? Model.SystemName).Truncate(30, "…"));
}

@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">

            @if (Model.IconUrl.HasValue())
            {
                <img src="@Url.Content(Model.IconUrl)" class="img-responsive" alt="@Model.FriendlyName" />
            }
			
			@ViewBag.Title
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="btn btn-warning">
				<i class="fa fa-save"></i>
				<span>@T("Admin.Common.Save")</span>
			</button>
        </div>
    </div>
	
    @Html.ValidationSummary(false)
	@Html.HiddenFor(model => model.SystemName)
	
	@(Html.LocalizedEditor<ProviderModel, ProviderLocalizedModel>("provider-localized",
	@<table class="adminContent">
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.Locales[item].FriendlyName)
			</td>
			<td class="adminData">
				@*IMPORTANT: Do not delete, this hidden element contains the id to assign localized values to the corresponding language *@
				@Html.HiddenFor(model => model.Locales[item].LanguageId)

				@Html.EditorFor(model => Model.Locales[item].FriendlyName)
				@Html.ValidationMessageFor(model => model.Locales[item].FriendlyName)
			</td>
		</tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.Locales[item].Description)
			</td>
			<td class="adminData">
				@Html.TextAreaFor(model => Model.Locales[item].Description)
				@Html.ValidationMessageFor(model => model.Locales[item].Description)
			</td>
		</tr>
	</table>
	,
	@<table class="adminContent">
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.FriendlyName)
			</td>
			<td class="adminData">
				@Html.EditorFor(model => model.FriendlyName)
				@Html.ValidationMessageFor(model => model.FriendlyName)
			</td>
		</tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.Description)
			</td>
			<td class="adminData">
				@Html.TextAreaFor(model => model.Description)
				@Html.ValidationMessageFor(model => model.Description)
			</td>
		</tr>
	</table>
	))
}

Show Promotion Center/src/Presentation/SmartStore.Web/Administration/Views/Plugin/LicensePlugin.cshtml
@using SmartStore.Licensing
@model LicensePluginModel
@{
	Layout = null;
}
<form method="POST" action="@Url.Action("LicensePlugin", "Plugin", new { systemName = Model.SystemName })" data-systemname="@Model.SystemName"
	data-resetcheckurl="@Url.Action("LicenseResetStatusCheck", "Plugin", new { systemName = Model.SystemName })">

	@if (Model.InvalidDataStoreId == 0)
	{
		<table class="adminContent">
			@for (int i = 0; i < Model.StoreLicenses.Count; ++i)
			{
				var storeLicense = Model.StoreLicenses[i];
				var keyAttributes = new RouteValueDictionary(new { autocomplete = "off" });
				if (storeLicense.LicenseLabel.LicenseState == LicensingState.Licensed && string.IsNullOrWhiteSpace(storeLicense.LicenseKey) && !storeLicense.LicenseLabel.HideLabel)
				{
					keyAttributes.Add("disabled", "disabled");
				}
				<tr>
					<td colspan="2">
						<div class="admin-config-group@(i==0 ? "" : " mt-2")">
							<div class="title fs-h6">
								<span>
									@storeLicense.StoreName
								</span>
								<span class="license-label float-right">
									@Html.Partial("Partials/LicenseLabel", storeLicense.LicenseLabel)
								</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="adminTitle">
						@Html.SmartLabelFor(model => model.StoreLicenses[i].LicenseKey)
					</td>
					<td class="adminData">
						@Html.HiddenFor(model => model.StoreLicenses[i].StoreId)
						@Html.HiddenFor(model => model.StoreLicenses[i].StoreUrl)
						@Html.TextBoxFor(model => model.StoreLicenses[i].LicenseKey, keyAttributes)
					</td>
				</tr>
				<tr>
					<td class="adminTitle">
						<div class="ctl-label">
							<label>@T("Common.For", "")</label>
						</div>
					</td>
					<td class="adminData">
						<div class="form-control-plaintext">
							<span>@storeLicense.StoreUrl</span>
							<a href="@Url.Action("Edit", "Store", new { id = storeLicense.StoreId })">
								@T("Admin.Common.Change")
							</a>
						</div>
					</td>
				</tr>
			}
		</table>
	}
	else
	{
		<div class="alert alert-warning">
			<p>@T("Admin.Configuration.Plugins.LicensingInvalidStoreUrl")</p>
			<div>
				<a href="@Url.Action("Edit", "Store", new { id = Model.InvalidDataStoreId })" class="btn btn-warning">
					<span>@T("Admin.Common.Change")</span>
				</a>
			</div>
		</div>
	}
</form>