Show Promotion Center/src/Plugins/SmartStore.PayPal/Controllers/PayPalExpressController.cs
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Discounts;
using SmartStore.Core.Domain.Orders;
using SmartStore.Core.Domain.Shipping;
using SmartStore.Core.Logging;
using SmartStore.PayPal.Models;
using SmartStore.PayPal.PayPalSvc;
using SmartStore.PayPal.Settings;
using SmartStore.Services.Common;
using SmartStore.Services.Customers;
using SmartStore.Services.Directory;
using SmartStore.Services.Orders;
using SmartStore.Services.Payments;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Framework.Settings;
using System;
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;

namespace SmartStore.PayPal.Controllers
{
    public class PayPalExpressController : PayPalControllerBase<PayPalExpressPaymentSettings>
	{
		private readonly OrderSettings _orderSettings;
		private readonly ICurrencyService _currencyService;
		private readonly IOrderTotalCalculationService _orderTotalCalculationService;
		private readonly ICustomerService _customerService;
		private readonly IGenericAttributeService _genericAttributeService;

		public PayPalExpressController(
			IPaymentService paymentService,
			IOrderService orderService,
			IOrderProcessingService orderProcessingService,
			OrderSettings orderSettings,
			ICurrencyService currencyService,
			IOrderTotalCalculationService orderTotalCalculationService,
			ICustomerService customerService,
			IGenericAttributeService genericAttributeService) : base(
				PayPalExpressProvider.SystemName,
				paymentService,
				orderService,
				orderProcessingService)
		{
			_orderSettings = orderSettings;
			_currencyService = currencyService;
			_orderTotalCalculationService = orderTotalCalculationService;
			_customerService = customerService;
			_genericAttributeService = genericAttributeService;
		}

		private string GetCheckoutButtonUrl(PayPalExpressPaymentSettings settings)
		{
			var expressCheckoutButton = "~/Plugins/SmartStore.PayPal/Content/checkout-button-default.png";
            var cultureString = Services.WorkContext.WorkingLanguage.LanguageCulture;

            if (cultureString.StartsWith("en-"))
            {
                expressCheckoutButton = "~/Plugins/SmartStore.PayPal/Content/checkout-button-en.png";
            }
            else if (cultureString.StartsWith("de-"))
            {
                expressCheckoutButton = "~/Plugins/SmartStore.PayPal/Content/checkout-button-de.png";
            }

            return expressCheckoutButton;

        }

		[AdminAuthorize, ChildActionOnly, LoadSetting]
		public ActionResult Configure(PayPalExpressPaymentSettings settings, int storeScope)
		{
            var model = new PayPalExpressConfigurationModel();
            model.Copy(settings, true);

			PrepareConfigurationModel(model, storeScope);

			return View(model);
		}

		[HttpPost, AdminAuthorize, ChildActionOnly]
		public ActionResult Configure(PayPalExpressConfigurationModel model, FormCollection form)
		{
			var storeDependingSettingHelper = new StoreDependingSettingHelper(ViewData);
			var storeScope = this.GetActiveStoreScopeConfiguration(Services.StoreService, Services.WorkContext);
			var settings = Services.Settings.LoadSetting<PayPalExpressPaymentSettings>(storeScope);

			if (!ModelState.IsValid)
			{
				return Configure(settings, storeScope);
			}

			ModelState.Clear();
			model.Copy(settings, false);

			using (Services.Settings.BeginScope())
			{
				storeDependingSettingHelper.UpdateSettings(settings, form, storeScope, Services.Settings);
			}

			using (Services.Settings.BeginScope())
			{
				// Multistore context not possible, see IPN handling.
				Services.Settings.SaveSetting(settings, x => x.UseSandbox, 0, false);
			}

			NotifySuccess(T("Admin.Common.DataSuccessfullySaved"));

			return RedirectToConfiguration(PayPalExpressProvider.SystemName, false);
		}

		public ActionResult PaymentInfo()
		{
			var model = new PayPalExpressPaymentInfoModel();
			model.CurrentPageIsBasket = ControllerContext.ParentActionViewContext.RequestContext.RouteData.IsRouteEqual("ShoppingCart", "Cart");

			if (model.CurrentPageIsBasket)
			{
				var settings = Services.Settings.LoadSetting<PayPalExpressPaymentSettings>(Services.StoreContext.CurrentStore.Id);

				model.SubmitButtonImageUrl = GetCheckoutButtonUrl(settings);
			}

			return PartialView(model);
		}

		public ActionResult MiniShoppingCart()
		{
			var settings = Services.Settings.LoadSetting<PayPalExpressPaymentSettings>(Services.StoreContext.CurrentStore.Id);

			if (settings.ShowButtonInMiniShoppingCart)
			{
				var model = new PayPalExpressPaymentInfoModel();
				model.SubmitButtonImageUrl = GetCheckoutButtonUrl(settings);

				return PartialView(model);
			}

			return new EmptyResult();
		}

		public ActionResult SubmitButton()
		{
			try
			{
				//user validation
				if ((Services.WorkContext.CurrentCustomer.IsGuest() && !_orderSettings.AnonymousCheckoutAllowed))
					return RedirectToRoute("Login");

				var store = Services.StoreContext.CurrentStore;
				var customer = Services.WorkContext.CurrentCustomer;
				var settings = Services.Settings.LoadSetting<PayPalExpressPaymentSettings>(store.Id);
				var cart = Services.WorkContext.CurrentCustomer.GetCartItems(ShoppingCartType.ShoppingCart, store.Id);

				if (cart.Count == 0)
					return RedirectToRoute("ShoppingCart");

                if (String.IsNullOrEmpty(settings.ApiAccountName))
					throw new ApplicationException("PayPal API Account Name is not set");
                if (String.IsNullOrEmpty(settings.ApiAccountPassword))
					throw new ApplicationException("PayPal API Password is not set");
                if (String.IsNullOrEmpty(settings.Signature))
					throw new ApplicationException("PayPal API Signature is not set");

				var provider = PaymentService.LoadPaymentMethodBySystemName(PayPalExpressProvider.SystemName, true);
				var processor = provider != null ? provider.Value as PayPalExpressProvider : null;
				if (processor == null)
					throw new SmartException(T("Plugins.CannotLoadModule", T("Plugins.FriendlyName.Payments.PayPalExpress")));

				var processPaymentRequest = new PayPalProcessPaymentRequest();

                processPaymentRequest.StoreId = store.Id;

				//Get sub-total and discounts that apply to sub-total
				decimal orderSubTotalDiscountAmountBase = decimal.Zero;
				Discount orderSubTotalAppliedDiscount = null;
				decimal subTotalWithoutDiscountBase = decimal.Zero;
				decimal subTotalWithDiscountBase = decimal.Zero;

				_orderTotalCalculationService.GetShoppingCartSubTotal(cart,
					out orderSubTotalDiscountAmountBase, out orderSubTotalAppliedDiscount, out subTotalWithoutDiscountBase, out subTotalWithDiscountBase);

				//order total
				decimal resultTemp = decimal.Zero;
				resultTemp += subTotalWithDiscountBase;

				//Get discounts that apply to Total
				Discount appliedDiscount = null;
				var discountAmount = _orderTotalCalculationService.GetOrderTotalDiscount(customer, resultTemp, out appliedDiscount);

				//if the current total is less than the discount amount, we only make the discount equal to the current total        
				if (resultTemp < discountAmount)
					discountAmount = resultTemp;

				//reduce subtotal
				resultTemp -= discountAmount;

				if (resultTemp < decimal.Zero)
					resultTemp = decimal.Zero;

				decimal tempDiscount = discountAmount + orderSubTotalDiscountAmountBase;

				resultTemp = _currencyService.ConvertFromPrimaryStoreCurrency(resultTemp, Services.WorkContext.WorkingCurrency);
				if (tempDiscount > decimal.Zero)
				{
					tempDiscount = _currencyService.ConvertFromPrimaryStoreCurrency(tempDiscount, Services.WorkContext.WorkingCurrency);
				}

				processPaymentRequest.PaymentMethodSystemName = PayPalExpressProvider.SystemName;
				processPaymentRequest.OrderTotal = resultTemp;
				processPaymentRequest.Discount = tempDiscount;
				processPaymentRequest.IsRecurringPayment = false;

				//var selectedPaymentMethodSystemName = _workContext.CurrentCustomer.GetAttribute<string>(SystemCustomerAttributeNames.SelectedPaymentMethod, _storeContext.CurrentStore.Id);

				processPaymentRequest.CustomerId = Services.WorkContext.CurrentCustomer.Id;
				this.Session["OrderPaymentInfo"] = processPaymentRequest;

				var resp = processor.SetExpressCheckout(processPaymentRequest, cart);

				if (resp.Ack == AckCodeType.Success)
				{
					// Note: If Token is null and an empty page with "No token passed" is displyed, then this is caused by a broken
					// Web References/PayPalSvc/Reference.cs file. To fix it, check git history of the file and revert changes.
					processPaymentRequest.PaypalToken = resp.Token;
					processPaymentRequest.OrderGuid = new Guid();
					processPaymentRequest.IsShippingMethodSet = ControllerContext.RouteData.IsRouteEqual("ShoppingCart", "Cart");
					this.Session["OrderPaymentInfo"] = processPaymentRequest;

					_genericAttributeService.SaveAttribute<string>(customer, SystemCustomerAttributeNames.SelectedPaymentMethod, PayPalExpressProvider.SystemName, store.Id);

					var result = new RedirectResult(String.Format(settings.GetPayPalUrl() + "?cmd=_express-checkout&useraction=commit&token={0}", resp.Token));

					return result;
				}
				else
				{
					var error = new StringBuilder("We apologize, but an error has occured.<br />");
					foreach (var errormsg in resp.Errors)
					{
						error.AppendLine(String.Format("{0} | {1} | {2}", errormsg.ErrorCode, errormsg.ShortMessage, errormsg.LongMessage));
					}

					Logger.Error(new Exception(error.ToString()), resp.Errors[0].ShortMessage);
                    
                    NotifyError(error.ToString(), false);

                    return RedirectToAction("Cart", "ShoppingCart", new { area = "" });
				}
			}
			catch (Exception ex)
			{
				Logger.Error(ex);

                NotifyError(ex.Message, false);

                return RedirectToAction("Cart", "ShoppingCart", new { area = "" });

			}

Show Promotion Center/src/Plugins/SmartStore.PayPal/Views/PayPalExpress/Configure.cshtml
@using SmartStore.PayPal.Settings;
@using SmartStore.PayPal.Models;
@using SmartStore.Web.Framework;
@using SmartStore.Web.Framework.UI;
@model PayPalExpressConfigurationModel
@{
	Layout = "";
	Html.AddCssFileParts(true, "~/Plugins/SmartStore.PayPal/Content/smartstore.paypal.css");
}

<div class="plugin-actions">
	<button type="submit" name="save" class="btn btn-warning" value="save">
		<i class="fa fa-check"></i>
		<span>@T("Admin.Common.Save")</span>
	</button>
</div>

<div class="plugin-configuration">
	<div>
		<div class="alert alert-info alert-dismissible">
			@Html.Raw(T("Plugins.Payments.PayPalExpress.AdminInstruction"))
			<button class="close" data-dismiss="alert">&times;</button>
		</div>
	</div>
	<div>
		<a href="https://www.paypal.com/" target="_blank">
			<img src="@Url.Content("~/Plugins/SmartStore.PayPal/Content/branding.png")" alt="PayPal" />
		</a>
	</div>
</div>

@{ Html.RenderAction("StoreScopeConfiguration", "Setting", new { area = "Admin" }); }

@using (Html.BeginForm())
{
	<table class="adminContent configure-paypal-express">
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.TransactMode)
            </td>
            <td class="adminData">
				@Html.SettingEditorFor(model => model.TransactMode, Html.DropDownListFor(model => model.TransactMode, new List<SelectListItem>
				{
					new SelectListItem { Text = T("Plugins.Payments.PayPalExpress.ModeAuth"), Value = TransactMode.Authorize.ToString(), Selected = Model.TransactMode == TransactMode.Authorize },
					new SelectListItem { Text = T("Plugins.Payments.PayPalExpress.ModeAuthAndCapture"), Value = TransactMode.AuthorizeAndCapture.ToString(), Selected = Model.TransactMode == TransactMode.AuthorizeAndCapture }
				}))
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.UseSandbox)
            </td>
            <td class="adminData">
				@*multistore context not possible, see IPN handling*@
                @Html.EditorFor(model => model.UseSandbox)
                @Html.ValidationMessageFor(model => model.UseSandbox)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.ApiAccountName)
            </td>
            <td class="adminData">
                @Html.SettingEditorFor(model => model.ApiAccountName)
                @Html.ValidationMessageFor(model => model.ApiAccountName)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.ApiAccountPassword)
            </td>
            <td class="adminData">
                @Html.SettingEditorFor(model => model.ApiAccountPassword)
                @Html.ValidationMessageFor(model => model.ApiAccountPassword)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.Signature)
            </td>
            <td class="adminData">
                @Html.SettingEditorFor(model => model.Signature)
                @Html.ValidationMessageFor(model => model.Signature)
            </td>
        </tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.CallbackTimeout)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.CallbackTimeout)
				@Html.ValidationMessageFor(model => model.CallbackTimeout)
			</td>
		</tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.IpnChangesPaymentStatus)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.IpnChangesPaymentStatus)
				@Html.ValidationMessageFor(model => model.IpnChangesPaymentStatus)
			</td>
		</tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.ShowButtonInMiniShoppingCart)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.ShowButtonInMiniShoppingCart)
				@Html.ValidationMessageFor(model => model.ShowButtonInMiniShoppingCart)
			</td>
		</tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.NoShipmentAddress)
            </td>
            <td class="adminData">
                @Html.SettingEditorFor(model => model.NoShipmentAddress)
                @Html.ValidationMessageFor(model => model.NoShipmentAddress)
            </td>
        </tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.ConfirmedShipment)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.ConfirmedShipment)
				@Html.ValidationMessageFor(model => model.ConfirmedShipment)
			</td>
		</tr>
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.DefaultShippingPrice)
            </td>
            <td class="adminData">
                @Html.SettingEditorFor(model => model.DefaultShippingPrice, null, new { postfix = Model.PrimaryStoreCurrencyCode })
                @Html.ValidationMessageFor(model => model.DefaultShippingPrice)
            </td>
        </tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.AdditionalFee)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.AdditionalFee, null, new { postfix = Model.PrimaryStoreCurrencyCode })
				@Html.ValidationMessageFor(model => model.AdditionalFee)
			</td>
		</tr>
		<tr>
			<td class="adminTitle">
				@Html.SmartLabelFor(model => model.AdditionalFeePercentage)
			</td>
			<td class="adminData">
				@Html.SettingEditorFor(model => model.AdditionalFeePercentage)
				@Html.ValidationMessageFor(model => model.AdditionalFeePercentage)
			</td>
		</tr>
    </table>
}

Show Promotion Center/src/Plugins/SmartStore.PayPal/Views/PayPalExpress/MiniShoppingCart.cshtml
@model SmartStore.PayPal.Models.PayPalExpressPaymentInfoModel

<div class="external-checkout-button">
	<a id="paypal-express-button" href="@Url.Action("SubmitButton", "PayPalExpress", new { area = "SmartStore.PayPal" })">
        <img src="@Url.Content(Model.SubmitButtonImageUrl)" />
	</a>
</div>

Show Promotion Center/src/Plugins/SmartStore.PayPal/Views/PayPalExpress/PaymentInfo.cshtml
@model SmartStore.PayPal.Models.PayPalExpressPaymentInfoModel
@{
    Layout = "";
}

@if (Model.CurrentPageIsBasket)
{
    <div id="paypal-checkout" class="my-2 ml-3">
        <a id="paypal-express-button" href="javascript:void(0)">
            <img alt="" src="@Url.Content(Model.SubmitButtonImageUrl)" />
        </a>
    </div>

	<script>
		$(function () {

			$('#paypal-express-button').on('click', function (e) {
				e.preventDefault();

				$.ajax({
					type: 'POST',
					url: '@Url.Action("SaveCartData", "ShoppingCart", new { area = "" })',
					data: $('#startcheckout').closest('form').serialize(),
					success: function (response) {
						if (response.success) {
							window.location = '@Url.Action("SubmitButton", "PayPalExpress", new { area = "SmartStore.PayPal" })';
						}
						else {
							displayNotification(response.message, 'error');
						}
					}
				});

				return false;
			});

		});
	</script>
}