Show Promotion Center/src/Presentation/SmartStore.Web/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web.Mvc;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Media;
using SmartStore.Services;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Services.Media;
using SmartStore.Services.Orders;
using SmartStore.Services.Search;
using SmartStore.Services.Security;
using SmartStore.Services.Seo;
using SmartStore.Services.Stores;
using SmartStore.Utilities;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Catalog;
using SmartStore.Web.Models.Media;
using SmartStore.Web.Models.Common;
using SmartStore.Web.Framework.UI;

namespace SmartStore.Web.Controllers
{
    
	public partial class CatalogController : PublicControllerBase
    {
		private readonly ICommonServices _services;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;
        private readonly ICategoryTemplateService _categoryTemplateService;
        private readonly IManufacturerTemplateService _manufacturerTemplateService;
        private readonly ICurrencyService _currencyService;
        private readonly IPictureService _pictureService;
        private readonly IPriceFormatter _priceFormatter;
		private readonly IOrderReportService _orderReportService;
		private readonly IProductTagService _productTagService;
		private readonly IRecentlyViewedProductsService _recentlyViewedProductsService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IAclService _aclService;
		private readonly IStoreMappingService _storeMappingService;
		private readonly ICatalogSearchService _catalogSearchService;
		private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
		private readonly ICompareProductsService _compareProductsService;
        private readonly Lazy<ILanguageService> _languageService;
        private readonly CatalogHelper _helper;
		private readonly IBreadcrumb _breadcrumb;

		public CatalogController(
			ICommonServices services,
			ICategoryService categoryService,
            IManufacturerService manufacturerService, 
			IProductService productService,
            ICategoryTemplateService categoryTemplateService,
            IManufacturerTemplateService manufacturerTemplateService,
			ICurrencyService currencyService,
			IOrderReportService orderReportService,
			IProductTagService productTagService,
			IRecentlyViewedProductsService recentlyViewedProductsService,
            IPictureService pictureService,
            IPriceFormatter priceFormatter,
            ISpecificationAttributeService specificationAttributeService,
			ICompareProductsService compareProductsService,
			IGenericAttributeService genericAttributeService,
			IAclService aclService,
			IStoreMappingService storeMappingService,
			ICatalogSearchService catalogSearchService,
			MediaSettings mediaSettings, 
			CatalogSettings catalogSettings,
            Lazy<ILanguageService> languageService,
            CatalogHelper helper,
			IBreadcrumb breadcrumb)
        {
			_services = services;
			_categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _productService = productService;
            _categoryTemplateService = categoryTemplateService;
            _manufacturerTemplateService = manufacturerTemplateService;
            _currencyService = currencyService;
			_orderReportService = orderReportService;
			_productTagService = productTagService;
			_recentlyViewedProductsService = recentlyViewedProductsService;
			_compareProductsService = compareProductsService;
            _pictureService = pictureService;
            _priceFormatter = priceFormatter;
            _specificationAttributeService = specificationAttributeService;
            _genericAttributeService = genericAttributeService;
            _aclService = aclService;
			_storeMappingService = storeMappingService;
			_catalogSearchService = catalogSearchService;
            _mediaSettings = mediaSettings;
            _catalogSettings = catalogSettings;
            _languageService = languageService;
            _helper = helper;
			_breadcrumb = breadcrumb;
        }

        #region Categories
        [Authorize]
        [RequireHttpsByConfigAttribute(SslRequirement.No)]
        public ActionResult Category(int categoryId, CatalogSearchQuery query)
        {
			var category = _categoryService.GetCategoryById(categoryId);
            if (category == null || category.Deleted)
				return HttpNotFound();

            // Check whether the current user has a "Manage catalog" permission
            // It allows him to preview a category before publishing
            if (!category.Published && !_services.Permissions.Authorize(StandardPermissionProvider.ManageCatalog))
				return HttpNotFound();

            // ACL (access control list)
            if (!_aclService.Authorize(category))
				return HttpNotFound();

			// Store mapping
			if (!_storeMappingService.Authorize(category))
				return HttpNotFound();

			// 'Continue shopping' URL
			if (!_services.WorkContext.CurrentCustomer.IsSystemAccount)
			{
				_genericAttributeService.SaveAttribute(_services.WorkContext.CurrentCustomer,
					SystemCustomerAttributeNames.LastContinueShoppingPage,
					_services.WebHelper.GetThisPageUrl(false),
					_services.StoreContext.CurrentStore.Id);
			}

            var model = category.ToModel();
			if (query.IsSubPage && !_catalogSettings.ShowDescriptionInSubPages)
			{
				model.Description.ChangeValue(string.Empty);
			}

			_services.DisplayControl.Announce(category);

            // Category breadcrumb
			if (_catalogSettings.CategoryBreadcrumbEnabled)
			{
				_helper.GetCategoryBreadCrumb(category.Id, 0).Select(x => x.Value).Each(x => _breadcrumb.Track(x));
			}

			// Products
			int[] catIds = new int[] { categoryId };
			if (_catalogSettings.ShowProductsFromSubcategories)
			{
				// Include subcategories
				catIds = catIds.Concat(_helper.GetChildCategoryIds(categoryId)).ToArray();
			}

			query.WithCategoryIds(_catalogSettings.IncludeFeaturedProductsInNormalLists ? (bool?)null : false, catIds);

			var searchResult = _catalogSearchService.Search(query);
			model.SearchResult = searchResult;

			var mappingSettings = _helper.GetBestFitProductSummaryMappingSettings(query.GetViewMode());
			model.Products = _helper.MapProductSummaryModel(searchResult.Hits, mappingSettings);

			model.SubCategoryDisplayType = _catalogSettings.SubCategoryDisplayType;

			var customerRolesIds = _services.WorkContext.CurrentCustomer.CustomerRoles.Where(x => x.Active).Select(x => x.Id).ToList();
			int pictureSize = _mediaSettings.CategoryThumbPictureSize;
			var fallbackType = _catalogSettings.HideCategoryDefaultPictures ? FallbackPictureType.NoFallback : FallbackPictureType.Entity;

			var hideSubCategories = _catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.Hide 
				|| (_catalogSettings.SubCategoryDisplayType == SubCategoryDisplayType.AboveProductList && query.IsSubPage && !_catalogSettings.ShowSubCategoriesInSubPages);
			var hideFeaturedProducts = _catalogSettings.IgnoreFeaturedProducts || (query.IsSubPage && !_catalogSettings.IncludeFeaturedProductsInSubPages);

			// Subcategories
			if (!hideSubCategories)
			{
				var subCategories = _categoryService.GetAllCategoriesByParentCategoryId(categoryId);
				var allPictureInfos = _pictureService.GetPictureInfos(subCategories.Select(x => x.PictureId.GetValueOrDefault()));

				model.SubCategories = subCategories
					.Select(x =>
					{
						var subCatName = x.GetLocalized(y => y.Name);
						var subCatModel = new CategoryModel.SubCategoryModel
						{
							Id = x.Id,
							Name = subCatName,
							SeName = x.GetSeName(),
						};

						_services.DisplayControl.Announce(x);

					// prepare picture model
					var pictureInfo = allPictureInfos.Get(x.PictureId.GetValueOrDefault());

						subCatModel.PictureModel = new PictureModel
						{
							PictureId = pictureInfo?.Id ?? 0,
							Size = pictureSize,
							ImageUrl = _pictureService.GetUrl(pictureInfo, pictureSize, fallbackType),
							FullSizeImageUrl = _pictureService.GetUrl(pictureInfo, 0, FallbackPictureType.NoFallback),
							FullSizeImageWidth = pictureInfo?.Width,
							FullSizeImageHeight = pictureInfo?.Height,
							Title = string.Format(T("Media.Category.ImageLinkTitleFormat"), subCatName),
							AlternateText = string.Format(T("Media.Category.ImageAlternateTextFormat"), subCatName)
						};

						return subCatModel;
					})
					.ToList();
			}

			// Featured Products
			if (!hideFeaturedProducts)
			{
				CatalogSearchResult featuredProductsResult = null;

				string cacheKey = ModelCacheEventConsumer.CATEGORY_HAS_FEATURED_PRODUCTS_KEY.FormatInvariant(categoryId, string.Join(",", customerRolesIds), _services.StoreContext.CurrentStore.Id);
				var hasFeaturedProductsCache = _services.Cache.Get<bool?>(cacheKey);

				var featuredProductsQuery = new CatalogSearchQuery()
					.VisibleOnly(_services.WorkContext.CurrentCustomer)
					.VisibleIndividuallyOnly(true)
					.WithCategoryIds(true, categoryId)
					.HasStoreId(_services.StoreContext.CurrentStore.Id)
					.WithLanguage(_services.WorkContext.WorkingLanguage)
					.WithCurrency(_services.WorkContext.WorkingCurrency);

				if (!hasFeaturedProductsCache.HasValue)
				{

Show Promotion Center/src/Presentation/SmartStore.Web/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Core.Domain.Polls;
using SmartStore.Services.Customers;
using SmartStore.Services.Polls;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Models.Polls;

namespace SmartStore.Web.Controllers
{
	public partial class PollController : PublicControllerBase
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IPollService _pollService;
        private readonly IWebHelper _webHelper;
        private readonly ICacheManager _cacheManager;
		private readonly IStoreContext _storeContext;

        #endregion

        #region Constructors

        public PollController(
            IWorkContext workContext,
			IPollService pollService,
            IWebHelper webHelper,
			ICacheManager cacheManager,
			IStoreContext storeContext)
        {
            this._workContext = workContext;
            this._pollService = pollService;
            this._webHelper = webHelper;
            this._cacheManager = cacheManager;
			this._storeContext = storeContext;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected PollModel PreparePollModel(Poll poll, bool setAlreadyVotedProperty)
        {
            var model = new PollModel
            {
                Id = poll.Id,
                AlreadyVoted = setAlreadyVotedProperty && _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id),
                Name = poll.Name
            };

            var answers = poll.PollAnswers.OrderBy(x => x.DisplayOrder);

			foreach (var answer in answers)
			{
				model.TotalVotes += answer.NumberOfVotes;
			}

            foreach (var pa in answers)
            {
                model.Answers.Add(new PollAnswerModel
                {
                    Id = pa.Id,
                    Name = pa.Name,
                    NumberOfVotes = pa.NumberOfVotes,
                    PercentOfTotalVotes = model.TotalVotes > 0 ? ((Convert.ToDouble(pa.NumberOfVotes) / Convert.ToDouble(model.TotalVotes)) * Convert.ToDouble(100)) : 0,
                });
            }

            return model;
        }

        #endregion

        #region Methods

        [ChildActionOnly]
        public ActionResult PollBlock(string systemKeyword)
        {
            if (String.IsNullOrWhiteSpace(systemKeyword))
                return Content("");

            var cacheKey = string.Format(ModelCacheEventConsumer.POLL_BY_SYSTEMNAME_MODEL_KEY, systemKeyword, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                var poll = _pollService.GetPollBySystemKeyword(systemKeyword, _workContext.WorkingLanguage.Id);

                if (poll == null)
					return new PollModel { Id = 0 };	//we do not cache nulls. that's why let's return an empty record (ID = 0)

                return PreparePollModel(poll, false);
            });

            if (cachedModel == null || cachedModel.Id == 0)
                return Content("");

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = (PollModel)cachedModel.Clone();
            model.AlreadyVoted = _pollService.AlreadyVoted(model.Id, _workContext.CurrentCustomer.Id);
            model.SystemKeyword = systemKeyword;

            return PartialView(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Vote(int pollAnswerId)
        {
            var pollAnswer = _pollService.GetPollAnswerById(pollAnswerId);

			if (pollAnswer == null)
			{
				return Json(new	{ error = T("Polls.AnswerNotFound", pollAnswerId).Text });
			}

            var poll = pollAnswer.Poll;

			if (!poll.Published)
			{
				return Json(new	{ error = T("Polls.NotAvailable").Text });
			}

			if (_workContext.CurrentCustomer.IsGuest() && !poll.AllowGuestsToVote)
			{
				return Json(new	{ error = T("Polls.OnlyRegisteredUsersVote").Text });
			}

            bool alreadyVoted = _pollService.AlreadyVoted(poll.Id, _workContext.CurrentCustomer.Id);
            if (!alreadyVoted)
            {
                //vote
                pollAnswer.PollVotingRecords.Add(new PollVotingRecord
                {
                    PollAnswerId = pollAnswer.Id,
                    CustomerId = _workContext.CurrentCustomer.Id,
                    IpAddress = _webHelper.GetCurrentIpAddress(),
                    IsApproved = true
                });

                //update totals
                pollAnswer.NumberOfVotes = pollAnswer.PollVotingRecords.Count;

                _pollService.UpdatePoll(poll);
            }

            return Json(new
            {
                html = this.RenderPartialViewToString("_Poll", PreparePollModel(poll, true)),
            });
        }
        
        [ChildActionOnly]
        public ActionResult HomePagePolls()
        {
            var cacheKey = string.Format(ModelCacheEventConsumer.HOMEPAGE_POLLS_MODEL_KEY, _workContext.WorkingLanguage.Id, _storeContext.CurrentStore.Id);
            var cachedModel = _cacheManager.Get(cacheKey, () =>
            {
                return _pollService.GetPolls(_workContext.WorkingLanguage.Id, true, 0, int.MaxValue)
                    .Select(x => PreparePollModel(x, false))
                    .ToList();
            });

            //"AlreadyVoted" property of "PollModel" object depends on the current customer. Let's update it.
            //But first we need to clone the cached model (the updated one should not be cached)
            var model = new List<PollModel>();

            foreach (var p in cachedModel)
            {
                var pollModel = (PollModel)p.Clone();
                pollModel.AlreadyVoted = _pollService.AlreadyVoted(pollModel.Id, _workContext.CurrentCustomer.Id);
                pollModel.SystemKeyword = "Homepage";
                model.Add(pollModel);
            }

			if (model.Count == 0)
				return Content("");

            return PartialView(model);
        }

        #endregion
    }
}

Show Promotion Center/src/Presentation/SmartStore.Web/Views/Home/ContactUs.cshtml
@model ContactUsModel
@using SmartStore.Web.Models.Common;
@{
    Layout = "_Layout";

    Html.AddTitleParts(!String.IsNullOrEmpty(Model.MetaTitle) ? Model.MetaTitle : T("PageTitle.ContactUs").Text);
    Html.AddMetaDescriptionParts(Model.MetaDescription);
    Html.AddMetaKeywordParts(Model.MetaKeywords);
}

<div class="page contact-page">
	<div class="page-title">
		<h1 class="h2">@T("PageTitle.ContactUs")</h1>
	</div>

    @{ Html.RenderAction("TopicBlock", "Topic", new { systemName = "ContactUs", isLead = true, bodyOnly = true }); }

    <div class="page-body">

        @{ Html.RenderWidget("contactus_top"); }

        @if (Model.SuccessfullySent)
        {
            <div class="alert alert-success">
                @Model.Result
            </div>        
		}
		else
		{
			using (Html.BeginRouteForm("ContactUs", FormMethod.Post, new { @class = "contact-form" }))
			{
				if (!ViewData.ModelState.IsValid)
				{
					@Html.ValidationSummary(false)
				}

				if (this.EnableHoneypotProtection)
				{
					<div class="d-none">
						@Html.HoneypotField()
					</div>
				}

				@Html.ControlGroupFor(model => model.FullName, required: Model.FullNameRequired, breakpoint: "sm")
				@Html.ControlGroupFor(model => model.Email, required: true, breakpoint: "sm")
				
				<div class="form-group row">
					@Html.LabelFor(model => model.Enquiry, new { @class = "col-sm-3 col-form-label required" })
					<div class="col-sm-9">
						@Html.TextAreaFor(model => model.Enquiry, new { @class = "form-control", rows = "6", placeholder = T("ContactUs.Enquiry.Hint") })
						@Html.ValidationMessageFor(model => model.Enquiry)
					</div>
				</div>

                <div class="form-group row">
                    <div class="col col-sm-auto offset-sm-3 text-muted">
                        @T("Common.FormFields.Required.Hint")
                    </div>
                </div>

				<div class="row justify-content-end">
					<div class="col-sm-9">
						@{ Html.RenderWidget("gdpr_consent"); }
					</div>
				</div>
				
				if (Model.DisplayCaptcha)
				{
					<div class="form-group row">
						<div class="col col-sm-auto offset-sm-3 captcha-box">
							@Html.Raw(Html.GenerateCaptcha())
						</div>
					</div>
				}
                
				<div class="form-group row">
					<div class="col col-sm-auto offset-sm-3">
						<button type="submit" name="send-email" class="btn btn-primary btn-lg btn-block">
							@T("ContactUs.Button")
						</button>
					</div>
				</div>
            }
        }

        @{ Html.RenderWidget("contactus_bottom"); }

    </div>
</div>

Show Promotion Center/src/Presentation/SmartStore.Web/Views/Home/Index.cshtml
@{
	Layout = "_LayoutHome";
	Html.AddBodyCssClass("home");
}

<div class="page home-page">
    <div class="page-body">
		@{
			Html.RenderWidget("home_page_top");

			Html.RenderAction("TopicBlock", "Topic", new { systemName = "HomePageText", isLead = true });
			Html.RenderWidget("home_page_after_intro");

			Html.RenderAction("HomepageCategories", "Catalog");
			Html.RenderWidget("home_page_after_categories");

			Html.RenderAction("HomepageProducts", "Catalog");
			Html.RenderWidget("home_page_after_products");

			Html.RenderAction("HomepageBestSellers", "Catalog");
			Html.RenderWidget("home_page_after_bestsellers");

			Html.RenderAction("HomepageManufacturers", "Catalog");
			Html.RenderWidget("home_page_after_manufacturers");

			Html.RenderAction("PopularProductTags", "Catalog", new { area = "" });
			Html.RenderWidget("home_page_after_tags");

			Html.RenderAction("HomePageNews", "News");
			Html.RenderWidget("home_page_after_news");

			Html.RenderAction("HomePagePolls", "Poll");
			Html.RenderWidget("home_page_after_polls");

			@* TODO: (mc) find more intelligent way of rendering RecentlyViewedProductsBlock globally *@
            Html.RenderAction("RecentlyViewedProductsBlock", "Catalog", new { area = "" });

            Html.RenderWidget("home_page_bottom");
		}
    </div>
</div>

Show Promotion Center/src/Presentation/SmartStore.Web/Views/Home/StoreClosed.cshtml
@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.StoreClosed").Text);
	Html.AddBodyCssClass("store-closed");
}

<div class="page store-closed-page">
    <div class="page-title">
        <h1>@T("StoreClosed")</h1>
    </div>
    <div class="page-body">
        @T("StoreClosed.Hint")
    </div>
</div>